config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions

  root 'home#index'

  get 'home/index'

  get '/about' => 'home#about'

  post '/questions' => 'home#temp'

  get '/questions/:id' => 'home#question'

  post '/answers' => 'home#temp'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :question

  include HasGravatar

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar

  def gravatar
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers

  include HasGravatar

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create

    question = Question.find(params[:answer][:question_id])
    answer = question.answers.create(answer_params)

    # whene we create an answer an email is sent to the questioner prepare the email then send it
    # MainMailer.notify_question_author(answer).deliver_now if we want to deviler it now we should wait until it is executed
    # with deliver_later the line is executer in the background (it is used witha dapter for active job) we use the gem sucker_punch

    MainMailer.notify_question_author(answer).deliver_later

    # using coockies to remember data entred by a current user of the browser
    session[:current_user_email] = answer_params[:email]

    redirect_to question

  end

  private

  def answer_params

    params.require(:answer).permit(:email, :body)
  
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @questions = Question.order(created_at: :desc).all

  end

  def about
  end

  def temp
    redirect_to root_path
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show

    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc).all

  end

  def create

    Question.create(question_params)

    # using coockies to remember data entred by a current user of the browser
    session[:current_user_email] = question_params[:email]

    redirect_to root_path

  end

  private

  # secure the parameters

  def question_params
    params.require(:question).permit(:email, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_email
    session[:current_user_email]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_nav_bar.html.erb
<nav class="navbar navbar-light bg-warning">
  <a class="navbar-brand text-dark font-weight-bold">Ask any question about Health and dietary</a>
  <div>
      <span class="text-right"><%= current_user_email %></span>
      <button type="button" class="btn btn-success my-2 my-sm-0 font-weight-bold text-light" data-toggle="modal" data-target="#exampleModal" >Ask Question</button>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
    <div class="modal fade" id="answerModal" tabindex="-1" role="dialog" aria-labelledby="answerModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="answerModalLabel">New Answer</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <%= form_for :answer, url: '/answers', html: { class: 'p-2' } do %>
            <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
            <div class="modal-body">
                <div class="form-group">
                  <label for="inputEmail" class="col-form-label">E-mail:</label>
                  <input type="email" name="answer[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="@Email" required>
                </div>
                <div class="form-group">
                  <label for="InputAnswer" class="col-form-label">New Answer:</label>
                  <textarea class="form-control" name="answer[body]" id="InputAnswer" placeholder="Your answer" required></textarea>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-warning text-dark">Submit</button>
            </div>
          <% end %>

        </div>
      </div>
    </div>

app/views/home/_new_question_form.html.erb
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ask a question</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <%= form_for :question, url: '/questions', html: { class: 'p-2' } do %>
            <div class="modal-body">
                <div class="form-group">
                  <label for="inputEmail" class="col-form-label">E-mail:</label>
                  <input type="email" name="question[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="@Email" required>
                </div>
                <div class="form-group">
                  <label for="InputQuestion" class="col-form-label">New Question:</label>
                  <textarea class="form-control" name="question[body]" id="InputQuestion" placeholder="Ask any question" required></textarea>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-warning text-dark">Submit</button>
            </div>
          <% end %>

        </div>
      </div>
    </div>

app/views/home/about.html.erb
<h1>ABOUT my mini heathy forum</h1>

app/views/home/index.html.erb
<div class='container-fluid'>
  <div class="row p-4">
    <div class="col">
      <h4 class="text-center text-primary font-weight-bold">About this mini-Forum</h4>
      <p class="text-center">Ask any question about nutrition or health in general a,d our expert will answer you!</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 p-4">
      <div class="boxes">
        <% @questions.each do |q| %>
          <div class="media mb-2" data-target="<%= question_path(q) %>">
            <img src="<%= q.gravatar %>" class="mr-3" alt="avatar">
            <div class="media-body">
              <h5 class="mt-0 mb-0"><%= q.email %> asked:</h5>
              <div class="text-secondary"><%= time_ago_in_words q.created_at %> ago ..</div>
              <%= q.body %>
            </div>
          </div>
          <a href="<%= question_path(q) %>" class="btn btn-outline-dark btn-sm btn-block mb-4">
            Clic here to View the expert's answers
          </a>
        <% end %>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <% if @questions.empty? %>
    <div class="alert alert-info">Be the first to ask!</div>
  <% end %>
</div>

app/views/home/question.html.erb
<div class='container-fluid'>
  <div class="row p-4">
    <div class="col">
      <p class="text-center">Answers for this question</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-10 p-4">
      <div class="media mb-2">
        <img src="http://www.gravatar.com/avatar/424242" class="mr-3" alt="avatar">
        <div class="media-body">
          <h5 class="mt-0 ">user@mail.com</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>
      <a href="/questions/12" type="button" class="btn btn-outline-dark btn-sm btn-block" data-toggle="modal" data-target="#answerModal">
        Clic here to answer this question
      </a>

      <%= render 'home/new_answer_form'%>

    </div>
    <div class="col">
    </div>
  </div>

  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 p-4">
      <div class="media">
        <img src="http://www.gravatar.com/avatar/424242" class="mr-3" alt="avatar">
        <div class="media-body">
          <h5 class="mt-0 ">user@mail.com Answers:</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>
    </div>
    <div class="col">
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniHealthForum</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/nav_bar'%>

    <div class="container-fluid bg-light">
      <%= yield %>
    </div>

    <!-- Modal pop-up window -->

    <%= render 'home/new_question_form'%>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/questions/show.html.erb
<div class='container-fluid'>

  <div class="row p-4">
    <div class="col">
      <p class="text-center">Answers for this question</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
    </div>
    <div class="col-10 p-4">
      <div class="media mb-2">
        <img src="<%= @question.gravatar %>" class="mr-3" alt="avatar">
        <div class="media-body">
          <h5 class="mt-0 mb-0"><%= @question.email %> asked:</h5>
              <div class="text-secondary"><%= time_ago_in_words @question.created_at %> ago ..</div>
              <%= @question.body %>
        </div>
      </div>
      <a href="/questions/12" type="button" class="btn btn-outline-dark btn-sm btn-block" data-toggle="modal" data-target="#answerModal">
        Clic here to answer this question
      </a>

      <%= render 'home/new_answer_form'%>

    </div>
    <div class="col">
    </div>
  </div>

  <div class="row">
    <div class="col">
    </div>
    <div class="col-6 p-4">

      <% @answers.each do |a| %>
        <div class="media mb-2">
            <img src="<%= a.gravatar %>" class="mr-3" alt="avatar">
            <div class="media-body">
              <h5 class="mt-0 mb-0"><%= a.email %> answered:</h5>
              <div class="text-secondary"><%= time_ago_in_words a.created_at %> ago ..</div>
              <%= a.body %>
            </div>
        </div>
      <% end %>

    </div>
    <div class="col">
    </div>
  </div>

  <% if @question.answers.empty? %>
    <div class="alert alert-info">Waiting for answers!</div>
  <% end %>

</div>